export type Rate = {passed:number;failed:number;decided:number;rate:number|null};
export type Timing = {samples:number;missing:number;meanMs:number|null;medianMs:number|null;p90Ms:number|null};
export type StagePerformance = {submitted:number;submissions:number;firstPass:Rate;recheck:Rate;firstRecheck:Rate;duration:Timing;qualityWait:Timing;
  pending:number;excluded:number;coverage:{eligible:number;sampled:number;unresolved:number;rate:number|null}};
export type OperatorSummary = {submitted:number;submissions:number;released:number;rereleased:number;delivered:number;deliveredBatches:number;returned:number;returnRounds:number;
  repeatedReturns:number;reworked:number;reworkRounds:number;batchAffected:number;reworkDuration:Timing;pending:number;waitingQuality:number;longWaiting:number;
  COPY:StagePerformance;IMAGE:StagePerformance;reasons:{code:string;count:number}[]};
export type OperatorPerson = OperatorSummary & {accountId:number;username:string;displayName:string};
export type OperatorReport = {metricVersion:number;timezone:string;asOf:string;range:{from:string;to:string};snapshotToken:string;expiresAt:string;
  summary:OperatorSummary;people:{items:OperatorPerson[];total:number;page:number;pageSize:number};
  trend:{date:string;submitted:number;released:number;COPY:Rate;IMAGE:Rate}[];
  dataQuality:{unknownIdentity:number;excluded:{reason:string;count:number}[];timingSince:string|null;historyNotice:string}};
export type OperatorEvent = {id:string;taskId:number;accountId:number|null;stage:'COPY'|'IMAGE';kind:string;at:string;query:string;
  username:string;displayName:string;canOpen?:boolean;copyRevisionId?:number;imageRunId?:string;samplingItemId?:number;reviewerId?:number;outcome?:string;
  first?:boolean;sampleKind?:string;rework?:boolean;returnedAt?:string;returnRound?:number;reasons?:string[];target?:string;exclusion?:string;
  submittedAt?:string;releaseMethod?:string;timing?:{humanMs:number|null;backgroundMs:number|null;qualityWaitMs:number|null;reason:string|null}};
export type OperatorDetail = {person:OperatorPerson;asOf:string;range:{from:string;to:string};items:OperatorEvent[];total:number;page:number;pageSize:number;
  trend:{date:string;submitted:number;returned:number;COPY:Rate;IMAGE:Rate}[];
  current:{taskId:number;query:string;phase:string;stage:string;waitingMs:number}[];
  timeline:{id:number;taskId:number;accountId:number|null;stage:string;phase:string;at:string;baseline:boolean}[]};
