import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { join, resolve } from 'node:path';
import test from 'node:test';
import { DEFAULT_HUMAN_QUALITY_SETTINGS } from '../src/human-quality-settings.mjs';
import { DEFAULT_IMAGE_SETTINGS } from '../server/src/image-options.mjs';

test('copy review browser: body and tag controls, original/final ratings, rework save, read-only gates and actual history', {
  skip: process.env.RUN_COPY_REVIEW_CONTROLS_BROWSER !== '1', timeout: 180_000,
}, async () => {
  const { build } = await import('esbuild'); const { chromium } = await import('playwright-core');
  const base = resolve('.codex_artifacts/copy-review-controls'); await mkdir(base, { recursive: true }); const directory = await mkdtemp(join(base, 'browser-'));
  await build({ stdin: { contents: `import './app/globals.css';import React from'react';import{createRoot}from'react-dom/client';import{TaskReviewDialog}from'./app/workbench/task-review-dialog';import{ConfirmDialogProvider}from'./components/ui/confirm-dialog';import{TextInputDialogProvider}from'./components/ui/text-input-dialog';import{BackgroundTasksProvider}from'./app/components/background-tasks';import{Toaster}from'./components/ui/sonner';const admin=location.search.includes('admin');createRoot(document.getElementById('root')).render(<ConfirmDialogProvider><TextInputDialogProvider><BackgroundTasksProvider accountKey="controls" accountUsername="reviewer" accountId={7}><TaskReviewDialog taskId={41}nodeId="fixture"role={admin?'ADMIN':'USER'}currentUsername="reviewer"currentAccountId={7}embedded onOpenChange={()=>{}}onUpdated={async message=>{window.__updated=message}}/><Toaster/></BackgroundTasksProvider></TextInputDialogProvider></ConfirmDialogProvider>);`, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, outfile: join(directory, 'bundle.js'), jsx: 'automatic', platform: 'browser', conditions: ['style'], alias: { '@': process.cwd() }, define: { 'process.env.NODE_ENV': '"test"', 'process.env': '{}' } });
  const js = await readFile(join(directory, 'bundle.js')), rawCss = await readFile(join(directory, 'bundle.css'), 'utf8');
  const { default: postcss } = await import('postcss'), { default: tailwind } = await import('@tailwindcss/postcss'); const { css } = await postcss([tailwind()]).process(rawCss, { from: resolve('app/globals.css') });
  const originalCopy = { title: '合成原稿', body: '文'.repeat(420), tags: ['#整理', '#办公', '#示例'] };
  const originalRevision = { id: 12, revision: 1, approvedAt: null, content: { copy: originalCopy, imageSettings: DEFAULT_IMAGE_SETTINGS, imagePlan: ['hero', 'steps', 'summary'].map((kind, i) => ({ kind, headline: `合成第${i+1}页`, subtitle: '', bullets: ['第一条合成要点', '第二条合成要点'], prompt: '整洁的桌面与自然光，文字清晰' })) } };
  let task = {}, fails = false, planFails = true, planJob = null, browser; const requests = [], errors = [];
  const reset = (scenario = 'normal') => { task = { id: 41, query: '合成功能验证需求', state: scenario === 'qc' ? 'COPY_QC_PENDING' : scenario === 'delivery' ? 'REVIEWED' : 'COPY_REVIEW_PENDING', currentStage: scenario === 'qc' ? 'QC_PENDING' : undefined, assignedToUserId: scenario === 'unassigned' ? null : scenario === 'other' ? 'peer' : 'reviewer', assignedToAccountId: scenario === 'unassigned' ? null : scenario === 'other' ? 8 : 7, currentCopyRevisionId: 12, currentImageRunId: null, deliveryStatus: scenario === 'delivery' ? 'READY' : undefined, aiDisclosureEnabled: false, copyRevisions: [structuredClone(originalRevision)], imageRuns: [], assets: [], humanQualityAssessments: [], mandatoryCopyQc: scenario === 'rework', mandatoryCopyQcOrigin: scenario === 'rework' ? 'FINAL_REWORK' : null }; if (scenario === 'rework') { task.copyRevisions[0].revisionOrigin = 'FINAL_REWORK'; task.copyRevisions[0].reworkTarget = 'BOTH'; } };
  reset(); const archive = Buffer.from('synthetic archive bytes; file-format validation is in the real 100-data suite');
  const server = createServer(async (request, response) => {
    const url = new URL(request.url, 'http://localhost'), p = url.pathname;
    if (p === '/bundle.js') { response.setHeader('content-type', 'application/javascript'); response.end(js); return; }
    if (p === '/bundle.css') { response.setHeader('content-type', 'text/css'); response.end(css); return; }
    if (!p.startsWith('/api/')) { response.setHeader('content-type', 'text/html; charset=utf-8'); response.end(p === '/copy-qa' ? '<h1>Fixture QA destination</h1>' : '<html><meta charset="utf-8"><link rel="stylesheet"href="/bundle.css"><div id="root"></div><script src="/bundle.js"></script></html>'); return; }
    let raw = ''; for await (const chunk of request) raw += chunk; const body = raw ? JSON.parse(raw) : null; requests.push({ method: request.method, path: p, query: Object.fromEntries(url.searchParams), body });
    const reply = (data, status = 200) => { response.statusCode = status; response.setHeader('content-type', 'application/json'); response.end(JSON.stringify(status >= 400 ? { error: { code: 'FIXTURE', message: data } } : { data })); };
    if (p === '/api/human-quality-settings') { reply(DEFAULT_HUMAN_QUALITY_SETTINGS); return; }
    if (p === '/api/control-plane/health') { reply({ capabilities: { imageResume: true } }); return; }
    if (p.endsWith('/tasks/41')) { reply(task); return; }
    if (p.endsWith('/image-capabilities')) { reply({ version: 1, reviewImagePlanEdits: true }); return; }
    if (p.endsWith('/copy-review-drafts')) { reply({ baseCopyRevisionId: task.currentCopyRevisionId, drafts: [] }); return; }
    if (p.endsWith('/regenerate-image-plan')) { if (planFails) { reply('temporary plan generation failure', 503); return; } planJob = { id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', status: 'SUCCEEDED', requestedByUsername: 'reviewer', requestedByAccountId: 7, copyRevisionId: task.currentCopyRevisionId, copy: body.copy, result: { imagePlan: originalRevision.content.imagePlan.map(item => ({ ...item, headline: '失败后重新生成的规划' })), model: 'fixture-only' } }; reply({ created: true, job: planJob }); return; }
    if (p.includes('/regenerate-image-plan/')) { reply(planJob); return; }
    if (p.endsWith('/retry') || p.endsWith('/retry-image') || p.endsWith('/image-revisions')) { if (fails) { reply('temporary image continuation failure', 503); return; } task.state = 'IMAGE_QUEUED'; reply(task); return; }
    if (p.endsWith('/approve-copy')) { if (body.edits && (body.edits.copy.tags.length < 3 || body.edits.copy.tags.length > 8)) { reply('标签必须为3至8个', 400); return; } if (fails) { reply('temporary copy failure', 503); return; } if (body.edits) { task.currentCopyRevisionId++; task.copyRevisions.push({ id: task.currentCopyRevisionId, revision: 2, content: body.edits, revisionOrigin: 'HUMAN_EDIT', reworkOrigin: task.mandatoryCopyQcOrigin }); } task.aiDisclosureEnabled = body.aiDisclosureEnabled; task.state = body.decision === 'DISCARD' ? 'CANCELLED' : body.decision === 'APPROVE' ? 'COPY_QC_PENDING' : 'COPY_REVIEW_PENDING'; reply(task); return; }
    if (p.endsWith('/archive')) { response.setHeader('content-type', 'application/zip'); response.setHeader('content-disposition', 'attachment; filename="fixture.zip"'); response.setHeader('content-length', archive.length); response.end(archive); return; }
    if (p.includes('/history/')) { const pieces = p.split('/'), kind = pieces[pieces.indexOf('history')+1], id = pieces[pieces.indexOf('history')+2]; if (id) { reply({ item: kind === 'copyRevisions' ? originalRevision : kind === 'assessments' ? { score: 2.5, action: 'APPROVE', note: '实际点击评分历史说明' } : { status: 'FAILED', stage: 'IMAGE', error: '合成错误' }, assets: [] }); } else reply({ items: [{ id: kind === 'copyRevisions' ? 12 : 801, revision: kind === 'copyRevisions' ? 1 : undefined, score: 2.5, createdAt: '2026-10-02T08:00:00Z' }], hasMore: !url.searchParams.has('cursor'), nextCursor: url.searchParams.has('cursor') ? null : 'next-fixture' }); return; }
    reply(`Unexpected fixture ${request.method} ${p}`, 404);
  });
  await new Promise(done => server.listen(0, '127.0.0.1', done));
  try {
    browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chromium-headless-shell' }); const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }); page.on('pageerror', error => errors.push(error.message)); const origin = `http://127.0.0.1:${server.address().port}`;
    const open = async scenario => { reset(scenario); await page.goto(origin + '/?scenario=' + scenario + (scenario === 'qc' || scenario === 'delivery' ? '&admin=1' : '')); await page.locator('#review-copy-title').waitFor(); };
    const postCount = () => requests.filter(row => row.method === 'POST').length;
    const submit = page.getByRole('button', { name: '提交并下一条', exact: true });
    await open('normal');
    const bullets = page.locator('#review-plan-bullets-0');
    const initialBullets = await bullets.inputValue();
    for (const count of [4, 5]) {
      await bullets.fill(Array.from({ length: count }, (_, index) => `第${index + 1}条合成要点：核对信息和适用范围，确保换行后的文字也完整显示`).join('\n'));
      await page.waitForFunction(() => {
        const element = document.querySelector('#review-plan-bullets-0');
        return element.scrollHeight <= element.clientHeight + 1;
      });
      assert.equal(await bullets.evaluate(element => element.scrollHeight > element.clientHeight + 1), false,
        `${count} long bullet lines stay complete even when the body is short`);
    }
    await bullets.fill(initialBullets);
    await page.locator('.workbench-copy-original-rating label[data-score="2.5"]').click(); assert.equal(await page.locator('input[type="radio"][value="2.5"]').isChecked(), true); await page.locator('textarea[id*="note"]').first().fill('合成原稿需要补充细节');
    const body = page.locator('#review-copy-body'), tags = page.locator('#review-copy-tags');
    await body.fill('文'.repeat(399)); assert.match(await page.locator('label[for="review-copy-body"]').innerText(), /399\/400–600/); const before = postCount(); await submit.click(); assert.equal(postCount(), before); assert.equal(await body.evaluate(element => element.validity.tooShort), true);
    await body.fill('文'.repeat(600)); await body.press('End'); await body.pressSequentially('文'); assert.equal((await body.inputValue()).length, 600); assert.equal(await body.getAttribute('maxlength'), '600');
    await body.fill('资料 '.repeat(100).trim() + '示例'); assert.match(await page.locator('label[for="review-copy-body"]').innerText(), /[0-9]+\/400–600/); await body.fill('文'.repeat(400));
    for (const values of [['#一', '#二'], Array.from({ length: 9 }, (_, i) => '#标签'+i)]) { await tags.fill(values.join(' ')); await submit.click(); await page.getByRole('alert').filter({ hasText: '标签必须为3至8个' }).waitFor().catch(async error => { console.log(JSON.stringify({ requests: requests.slice(-5), state: await page.evaluate(() => ({ text: document.body.innerText, invalid: [...document.querySelectorAll('input,textarea')].filter(element => element.willValidate && !element.validity.valid).map(element => ({ id: element.id, value: element.value, message: element.validationMessage })) })) })); throw error; }); assert.equal(task.state, 'COPY_REVIEW_PENDING'); assert.equal(await tags.inputValue(), values.join(' ')); }
    await tags.fill('#一 #二 #三 #四 #五 #六 #七 #八'); await page.locator('label.workbench-ai-disclosure-toggle').click(); assert.equal(await page.getByRole('checkbox', { name: /AI生成水印/ }).isChecked(), true); await page.getByRole('status', { name: '最终稿评分', exact: true }).waitFor();
    fails = true; await submit.click(); await page.getByRole('alert').filter({ hasText: 'temporary copy failure' }).waitFor(); assert.equal(await tags.inputValue(), '#一 #二 #三 #四 #五 #六 #七 #八'); const failed = requests.findLast(row => row.path.endsWith('/approve-copy')).body;
    fails = false; await submit.click(); await page.waitForFunction(() => window.__updated?.includes('最终修改稿')); const approved = requests.findLast(row => row.path.endsWith('/approve-copy')).body;
    assert.equal(approved.score, 3); assert.equal(approved.originalScore, 2.5); assert.equal(approved.originalNote, '合成原稿需要补充细节'); assert.equal(approved.edits.copy.body.length, 400); assert.equal(approved.edits.copy.tags.length, 8); assert.equal(approved.aiDisclosureEnabled, true); assert.equal(approved.reviewSessionId, failed.reviewSessionId);
    await open('discard'); await page.locator('.workbench-copy-original-rating label[data-score="1"]').click(); assert.equal(await page.locator('input[type="radio"][value="1"]').isChecked(), true); const discard = page.getByRole('button', { name: '评分并废弃', exact: true }); assert.equal(await discard.isDisabled(), true); await page.locator('textarea[id*="note"]').first().fill('合成原稿无法使用'); await discard.click(); const count = postCount(); await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click(); assert.equal(postCount(), count); await discard.click(); await page.getByRole('alertdialog').getByRole('button', { name: '评分并废弃', exact: true }).click(); await page.waitForFunction(() => window.__updated?.includes('已废弃')); const discarded = requests.findLast(row => row.path.endsWith('/approve-copy')).body; assert.equal(discarded.decision, 'DISCARD'); assert.equal(discarded.score, 1); assert.equal(discarded.edits, undefined);
    await open('rework'); assert.equal(await page.locator('input[type="radio"]').count(), 0); await page.locator('#review-copy-title').fill('已经实际修改的返工稿'); await page.getByRole('button', { name: '保存返工稿，暂不提交复检', exact: true }).click(); await page.waitForFunction(() => window.__updated?.includes('当前修改已保存')); const saved = requests.findLast(row => row.path.endsWith('/approve-copy')).body; assert.equal(saved.decision, 'SAVE'); assert.equal(saved.score, undefined); assert.equal(task.state, 'COPY_REVIEW_PENDING'); assert.equal(saved.edits.copy.title, '已经实际修改的返工稿');
    for (const scenario of ['unassigned', 'other', 'qc']) { await open(scenario); assert.equal(await page.locator('#review-copy-title').getAttribute('readonly'), ''); assert.equal(await page.getByRole('checkbox', { name: /AI生成水印/ }).isDisabled(), true); assert.equal(await submit.count(), 0); }
    await page.getByRole('link', { name: '进入质检批次', exact: true }).click(); await page.getByRole('heading', { name: 'Fixture QA destination', exact: true }).waitFor();
    await open('delivery'); const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('link', { name: '下载资源', exact: true }).click()]); const archivePath = join(directory, 'downloaded-fixture.zip'); await download.saveAs(archivePath); assert.deepEqual(await readFile(archivePath), archive);
    await page.getByRole('button', { name: /历史版本与审核记录/ }).click(); await page.getByRole('button', { name: /文案版本 · 第 1 版/ }).click(); await page.getByRole('heading', { name: '合成原稿', exact: true }).waitFor(); await page.getByRole('button', { name: '下一批历史', exact: true }).click(); await page.getByText('第 2 批', { exact: true }).waitFor(); await page.getByRole('button', { name: '上一批历史', exact: true }).click(); await page.getByText('第 1 批', { exact: true }).waitFor(); await page.getByRole('button', { name: '人工评分', exact: true }).click(); await page.getByRole('button', { name: /人工评分 · #801/ }).click(); await page.getByText('实际点击评分历史说明', { exact: true }).waitFor();
    await open('normal'); const oldHeadline = await page.locator('#review-plan-headline-0').inputValue(); await page.getByRole('button', { name: '按当前文案重新生成规划', exact: true }).click(); await page.getByRole('alert').filter({ hasText: 'temporary plan generation failure' }).waitFor(); assert.equal(await page.locator('#review-plan-headline-0').inputValue(), oldHeadline); assert.equal(await page.locator('#review-copy-title').inputValue(), originalCopy.title);
    planFails = false; await page.getByRole('button', { name: '按当前文案重新生成规划', exact: true }).click(); await page.waitForFunction(() => document.querySelector('#review-plan-headline-0')?.value === '失败后重新生成的规划'); assert.equal(await page.locator('#review-copy-title').inputValue(), originalCopy.title);
    const imageScenario = async scenario => { reset(); task.state = scenario === 'exhausted' ? 'COPY_REVIEW_PENDING' : 'IMAGE_FAILED'; task.currentStage = scenario === 'exhausted' ? 'IMAGE_RETRY_EXHAUSTED' : 'IMAGE_FAILED'; task.copyRevisions[0].approvedAt = '2026-10-02T08:00:00Z'; task.error = '合成图片生成失败'; await page.goto(origin + '/?admin=1&scenario=' + scenario); await page.locator('#review-copy-title').waitFor(); };
    await imageScenario('resume'); const resume = page.getByRole('button', { name: '从失败步骤继续', exact: true }); await resume.click(); let n = postCount(); await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click(); assert.equal(postCount(), n); fails = true; await resume.click(); await page.getByRole('alertdialog').getByRole('button', { name: '继续未完成步骤', exact: true }).click(); await page.getByRole('alert').filter({ hasText: 'temporary image continuation failure' }).waitFor(); fails = false; await resume.click(); await page.getByRole('alertdialog').getByRole('button', { name: '继续未完成步骤', exact: true }).click(); await page.waitForFunction(() => window.__updated?.includes('从失败步骤继续')); assert.deepEqual(requests.findLast(row => row.path.endsWith('/retry')).body, { useLatestConfig: false });
    await imageScenario('exhausted'); const retry = page.getByRole('button', { name: '重试生图', exact: true }); await retry.click(); n = postCount(); await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click(); assert.equal(postCount(), n); await retry.click(); await page.getByRole('alertdialog').getByRole('button', { name: '重试生图', exact: true }).click(); await page.waitForFunction(() => window.__updated?.includes('自动重试计数已重置')); assert.equal(requests.findLast(row => row.method === 'POST').path.endsWith('/retry-image'), true);
    await imageScenario('regenerate'); const regenerate = page.getByRole('button', { name: '重新生成图片', exact: true }); await regenerate.click(); n = postCount(); await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click(); assert.equal(postCount(), n); await regenerate.click(); await page.getByRole('alertdialog').getByRole('button', { name: '确认费用并生成整套', exact: true }).click(); await page.waitForFunction(() => window.__updated?.includes('随机选择布局')); const generated = requests.findLast(row => row.path.endsWith('/image-revisions')).body; assert.equal(generated.operation, 'REGENERATE'); assert.equal(generated.confirmation, 'LIVE_IMAGE_COST_ACCEPTED'); assert.equal(generated.layouts.length, 3);
    assert.deepEqual(errors, []); await page.screenshot({ path: join(directory, 'copy-controls-verified.png'), fullPage: true }); await writeFile(join(directory, 'evidence.json'), JSON.stringify({ modelCalls: 0, backend: 'isolated HTTP fakes; download bytes synthetic', featureIds: ['F-COPY-002','F-COPY-005','F-COPY-007','F-COPY-008','F-COPY-010','F-COPY-020','F-COPY-024','F-COPY-025','F-TRACE-001','F-PLAN-016','F-IREVIEW-017'], requests, errors }, null, 2)); console.log(`Copy controls browser evidence: ${directory}`);
  } finally { await browser?.close(); server.closeAllConnections(); await new Promise(done => server.close(done)); }
});
