import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import test from 'node:test';
import { DEFAULT_IMAGE_SETTINGS } from '../server/src/image-options.mjs';

test('history browser: actual lazy image versions, source/delivery preview, parameters and retry; knowledge SSR failure reload', {
  skip: process.env.RUN_HISTORY_KNOWLEDGE_BROWSER !== '1', timeout: 150_000,
}, async () => {
  const { build } = await import('esbuild'), { chromium } = await import('playwright-core');
  const directoryRoot = resolve('.codex_artifacts/history-knowledge'); await mkdir(directoryRoot, { recursive: true }); const directory = await mkdtemp(join(directoryRoot, 'browser-'));
  await build({ stdin: { contents: `import './app/globals.css';import React from'react';import{createRoot}from'react-dom/client';import{LazyImageHistory}from'./app/workbench/lazy-image-history';import{ImagePreview}from'./app/components/image-preview';createRoot(document.getElementById('root')).render(<><ImagePreview src="/api/control-plane/v1/assets/99"alt="当前成品"/><LazyImageHistory taskId={41}runs={[]}currentRunId="current"assets={[]}onRestore={settings=>{window.__restored=settings}}/></>);`, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, outfile: join(directory, 'bundle.js'), platform: 'browser', jsx: 'automatic', conditions: ['style'], alias: { '@': process.cwd() }, define: { 'process.env.NODE_ENV': '"test"' } });
  await build({ stdin: { contents: `import React from'react';import Page from'./app/knowledge/page';import{ConfirmDialogProvider}from'./components/ui/confirm-dialog';import{TextInputDialogProvider}from'./components/ui/text-input-dialog';export default async function(props){return <ConfirmDialogProvider><TextInputDialogProvider>{await Page(props)}</TextInputDialogProvider></ConfirmDialogProvider>}`, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, outfile: join(directory, 'knowledge-page.mjs'), format: 'esm', platform: 'node', packages: 'external', jsx: 'automatic', loader: { '.css': 'empty' }, alias: { '@': process.cwd() }, plugins: [{ name: 'isolated-SSR-services', setup(plugin) {
    plugin.onResolve({ filter: /(?:server-session|knowledge-runtime\.mjs|admin\/http\.mjs|next\/navigation|next\/link|next\/dynamic)$/ }, args => ({ path: args.path, namespace: 'SSR-fixture' }));
    plugin.onLoad({ filter: /.*/, namespace: 'SSR-fixture' }, args => ({ loader: 'jsx', resolveDir: process.cwd(), contents: args.path.endsWith('server-session') ? 'export const readServerSession=async()=>({roles:["ADMIN"],username:"fixture",accountId:7});'
      : args.path.endsWith('knowledge-runtime.mjs') ? `export const listAllKnowledge=async()=>[];export const withKnowledgeStore=async work=>work({remote:true,listCopyKnowledgeOverview:async()=>{if(globalThis.__fixtureKnowledgeFails)throw Error('synthetic knowledge service unavailable');return{data:[],pagination:{page:1,pageSize:10,totalItems:0,totalPages:1},labels:[]}},listCopyAnalysisPrompts:async()=>[],getProductionSettings:async()=>({settings:{knowledgeEnabled:true}})});`
      : args.path.endsWith('http.mjs') ? 'export class ApiError extends Error{constructor(status,message){super(message);this.status=status}}'
      : args.path.endsWith('navigation') ? 'export const redirect=url=>{throw Error("Unexpected fixture redirect "+url)};const router={replace(){},refresh(){}};export const useRouter=()=>router;export const usePathname=()=>"/knowledge";'
      : args.path.endsWith('dynamic') ? 'export default function dynamic(){return()=>null}'
      : 'import React from"react";export default function Link({children,...props}){return <a {...props}>{children}</a>}' }));
  } }] });
  const { default: KnowledgePage } = await import(pathToFileURL(join(directory, 'knowledge-page.mjs'))); const { renderToStaticMarkup } = await import('react-dom/server');
  const js = await readFile(join(directory, 'bundle.js')), rawCss = await readFile(join(directory, 'bundle.css'), 'utf8'); const { default: postcss } = await import('postcss'), { default: tailwind } = await import('@tailwindcss/postcss'); const { css } = await postcss([tailwind()]).process(rawCss, { from: resolve('app/globals.css') });
  const runs = ['old-1', 'old-2', 'old-3'].map((id, i) => ({ id, createdAt: `2026-10-0${i+1}T08:00:00Z`, status: 'COMPLETED', result: { images: [{ assetId: i+1, sourceUrl: `/v1/assets/${i+11}`, deliveryUrl: `/v1/assets/${i+1}?download=1`, imageSettings: { ...DEFAULT_IMAGE_SETTINGS, format: i === 1 ? 'JPEG' : 'PNG' }, transparency: { source: true, delivery: false } }], imageSettings: { ...DEFAULT_IMAGE_SETTINGS, format: i === 1 ? 'JPEG' : 'PNG' }, processing: { type: i === 1 ? 'REPROCESS' : 'REGENERATE' } } }));
  const image = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"width="80"height="100"><rect width="80"height="100"fill="green"/></svg>'); let fails = true, browser; const requests = [], errors = [];
  const server = createServer(async (request, response) => {
    const url = new URL(request.url, 'http://localhost'), p = url.pathname; requests.push({ method: request.method, path: p, query: Object.fromEntries(url.searchParams) });
    if (p === '/bundle.js') { response.setHeader('content-type', 'application/javascript'); response.end(js); return; }
    if (p === '/bundle.css') { response.setHeader('content-type', 'text/css'); response.end(css); return; }
    if (p === '/knowledge') { response.setHeader('content-type', 'text/html; charset=utf-8'); response.end('<html><meta charset="utf-8">'+renderToStaticMarkup(await KnowledgePage({ searchParams: Promise.resolve({}) }))+'</html>'); return; }
    if (p.includes('/assets/')) { response.setHeader('content-type', 'image/svg+xml'); if (url.searchParams.has('download')) response.setHeader('content-disposition', 'attachment; filename="synthetic-history.svg"'); response.end(image); return; }
    if (!p.startsWith('/api/')) { response.setHeader('content-type', 'text/html; charset=utf-8'); response.end('<html><meta charset="utf-8"><link rel="stylesheet"href="/bundle.css"><div id="root"></div><script src="/bundle.js"></script></html>'); return; }
    const reply = data => { response.setHeader('content-type', 'application/json'); response.end(JSON.stringify({ data })); };
    if (p.endsWith('/history/imageRuns')) { if (fails) { response.statusCode = 503; response.setHeader('content-type', 'application/json'); response.end(JSON.stringify({ error: { code: 'FIXTURE', message: 'synthetic image history unavailable' } })); return; } reply({ items: url.searchParams.has('cursor') ? runs.slice(2) : runs.slice(0, 2), hasMore: !url.searchParams.has('cursor'), nextCursor: url.searchParams.has('cursor') ? null : 'last' }); return; }
    if (p.includes('/history/imageRuns/')) { const item = runs.find(run => p.endsWith(run.id)); reply({ item, assets: [{ id: item.result.images[0].assetId, url: '/v1/assets/'+item.result.images[0].assetId }] }); return; }
    response.statusCode = 404; response.end('{}');
  });
  await new Promise(done => server.listen(0, '127.0.0.1', done));
  try {
    browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chromium-headless-shell' }); const page = await browser.newPage({ viewport: { width: 1400, height: 950 } }); page.on('pageerror', error => errors.push(error.message)); const origin = `http://127.0.0.1:${server.address().port}`;
    await page.goto(origin); await page.getByRole('button', { name: '历史图片 · 对照当前成品', exact: true }).click(); await page.getByRole('alert').filter({ hasText: 'synthetic image history unavailable' }).waitFor(); fails = false; await page.getByRole('button', { name: '重试历史图片', exact: true }).click();
    const version = page.getByLabel('查看历史版本', { exact: true }); await version.selectOption('old-2'); await page.getByRole('button', { name: '恢复此版本的格式与背景参数', exact: true }).waitFor(); await page.getByRole('button', { name: '恢复此版本的格式与背景参数', exact: true }).click(); assert.equal(await page.evaluate(() => window.__restored.format), 'JPEG');
    await page.getByRole('button', { name: '预览图片：历史版本第 1 张', exact: true }).click(); const preview = page.getByRole('dialog'); await preview.getByText('不透明图片 · JPEG', { exact: true }).waitFor(); await preview.getByRole('checkbox', { name: '查看处理前源图', exact: true }).check(); await preview.getByText('含透明像素', { exact: true }).waitFor(); await page.waitForFunction(() => document.querySelector('.image-preview-full')?.src.includes('/assets/12')); await preview.getByRole('checkbox', { name: '查看处理前源图', exact: true }).uncheck();
    const [download] = await Promise.all([page.waitForEvent('download'), preview.getByRole('link', { name: '下载交付文件', exact: true }).click()]); const file = join(directory, 'synthetic-history.svg'); await download.saveAs(file); assert.deepEqual(await readFile(file), image); await preview.getByRole('button', { name: '关闭图片预览', exact: true }).click();
    await page.getByRole('button', { name: '下一批图片版本', exact: true }).click(); await page.getByText('第 2 批', { exact: true }).waitFor(); await page.waitForFunction(() => document.querySelector('#image-history-41')?.value === 'old-3'); assert.equal(await version.inputValue(), 'old-3'); assert.equal(await page.getByRole('button', { name: '下一批图片版本', exact: true }).isDisabled(), true); await page.getByRole('button', { name: '上一批图片版本', exact: true }).click(); await page.getByText('第 1 批', { exact: true }).waitFor();
    globalThis.__fixtureKnowledgeFails = true; await page.goto(origin+'/knowledge'); await page.getByRole('heading', { name: '知识库暂时无法读取', exact: true }).waitFor(); await page.getByRole('alert').getByText('synthetic knowledge service unavailable', { exact: true }).waitFor(); globalThis.__fixtureKnowledgeFails = false; await page.getByRole('link', { name: '重新加载', exact: true }).click(); await page.getByRole('heading', { name: '文案知识库', exact: true }).waitFor(); assert.equal(await page.getByRole('alert').count(), 0);
    assert.deepEqual(errors, []); await page.screenshot({ path: join(directory, 'knowledge-recovered.png'), fullPage: true }); await writeFile(join(directory, 'evidence.json'), JSON.stringify({ featureIds: ['F-TRACE-002','F-IPREVIEW-011','F-KNOW-015'], evidenceType: 'real components and real KnowledgePage SSR with synthetic services', modelCalls: 0, requests, errors }, null, 2)); console.log(`History and SSR evidence: ${directory}`);
  } finally { delete globalThis.__fixtureKnowledgeFails; await browser?.close(); server.closeAllConnections(); await new Promise(done => server.close(done)); }
});
