import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, readFile, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import test from 'node:test';

test('shared delivery query browser: positive package and batch membership, archive and version branches, full pagination', {
  skip: process.env.RUN_SHARED_DELIVERY_FILTER_BROWSER !== '1', timeout: 120000,
}, async () => {
  const { build } = await import('esbuild'), { chromium } = await import('playwright-core');
  const root = await mkdtemp(join(tmpdir(), 'delivery-filter-browser-')); const out = resolve('reports/full-functional-2026-10-02'); await mkdir(out, { recursive: true });
  await build({ stdin: { contents: `import'./app/globals.css';import React from'react';import{createRoot}from'react-dom/client';import{SharedDeliveryWorkbench}from'./app/delivery-pool/shared-delivery-workbench';import{ConfirmDialogProvider}from'./components/ui/confirm-dialog';createRoot(document.getElementById('root')).render(<ConfirmDialogProvider><SharedDeliveryWorkbench role={location.pathname.includes('user')?'USER':'ADMIN'}/></ConfirmDialogProvider>);`, resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, outfile: join(root, 'bundle.js'), jsx: 'automatic', platform: 'browser', conditions: ['style'], alias: { '@': process.cwd() }, define: { 'process.env.NODE_ENV': '"test"' } });
  const { default: postcss } = await import('postcss'), { default: tailwind } = await import('@tailwindcss/postcss'); const { css } = await postcss([tailwind()]).process(await readFile(join(root, 'bundle.css'), 'utf8'), { from: resolve('app/globals.css') }); await writeFile(join(root, 'bundle.css'), css);
  const now = new Date().toISOString(); const rows = Array.from({ length: 125 }, (_, index) => ({ itemId: index + 1, entryId: index + 1, taskId: index + 1, query: `合成精确交付 ${index + 1}`, copyRevisionId: index + 100, imageRunId: '22345678-1234-4234-8234-123456789abc', packageName: index % 2 ? '精确词包-乙' : '精确词包-甲', clientBatchCode: (index % 2 ? 'b' : 'a').repeat(32), batchCode: index % 2 ? 'JF-beta' : 'JF-alpha', assigneeUsername: 'fixture-worker', ownerUsername: 'fixture-worker', state: 'DELIVERED', packedAt: now, packedBy: 'admin', deliveredAt: now, deliveredBy: 'fixture-worker', readyAt: now, updatedAt: now, archivedAt: index % 3 === 0 ? now : null, downloadedByMe: true, canConfirm: false, isCurrent: index % 5 !== 0, versionUpdated: index % 4 === 0, batchVisibleCount: 125, batchDeliveredCount: 125 }));
  const requests = [], evidence = [], errors = [], unexpected = [];
  const server = createServer(async (req, res) => {
    const url = new URL(req.url, 'http://fixture'); if (url.pathname === '/bundle.js' || url.pathname === '/bundle.css') { res.setHeader('content-type', url.pathname.endsWith('css') ? 'text/css' : 'text/javascript'); res.end(await readFile(join(root, url.pathname.slice(1)))); return; }
    const reply = data => { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ data })); };
    if (url.pathname.endsWith('/delivery-items')) {
      assert.equal(req.method, 'GET'); const p = Object.fromEntries(url.searchParams); requests.push(p);
      let values = rows.filter(row => (p.view === 'HISTORY' || row.isCurrent) && (!p.packageName || row.packageName === p.packageName) && (!p.clientBatchCode || row.clientBatchCode === p.clientBatchCode) && (!p.search || String(row.taskId) === p.search || row.query.includes(p.search) || row.batchCode.includes(p.search)) && (p.archiveState === 'ALL' || Boolean(row.archivedAt) === (p.archiveState === 'YES')) && (p.versionState === 'ALL' || p.versionState === 'UPDATED' && row.versionUpdated || p.versionState === 'HISTORICAL' && !row.isCurrent));
      const total = values.length; const offset = Number(p.offset), limit = Number(p.limit); values = values.slice(offset, offset + limit); reply({ items: values, total, summary: { total, delivered: total, packed: 0, unpacked: 0, updated: values.filter(row => row.versionUpdated).length }, updatedAt: now }); return;
    }
    if (url.pathname.endsWith('/users')) { reply([]); return; }
    if (url.pathname.endsWith('/delivery-archives')) { reply({ items: [], total: 0 }); return; }
    if (url.pathname.startsWith('/api/')) { unexpected.push(`${req.method} ${url.pathname}`); res.statusCode = 404; reply({}); return; }
    res.setHeader('content-type', 'text/html'); res.end('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><link rel="stylesheet" href="/bundle.css"><body style="padding:24px"><div id="root"></div><script src="/bundle.js"></script></body></html>');
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); const browser = await chromium.launch({ channel: 'msedge', headless: true }); const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } }); page.setDefaultTimeout(15000); page.on('pageerror', error => errors.push(error.message));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const select = async (label, option) => { await page.getByRole('combobox', { name: label, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click(); };
  const apply = async (action, expected) => { const responsePromise = page.waitForResponse(r => new URL(r.url()).pathname.endsWith('/delivery-items') && Object.entries(expected).every(([key, value]) => new URL(r.url()).searchParams.get(key) === String(value))); await action(); const response = await responsePromise; const data = (await response.json()).data; await page.waitForFunction(ids => { const nodes = [...document.querySelectorAll('input[aria-label^="选择交付任务 "]')]; return nodes.length === ids.length && nodes.every((node, index) => node.getAttribute('aria-label') === `选择交付任务 ${ids[index]}`); }, data.items.map(item => item.taskId)); evidence.push({ params: Object.fromEntries(new URL(response.url()).searchParams), total: data.total, taskIds: data.items.map(item => item.taskId) }); return data; };
  const query = expected => apply(() => page.getByRole('button', { name: '查询', exact: true }).click(), expected);
  try {
    await page.goto(origin); await page.getByRole('checkbox', { name: '选择交付任务 2', exact: true }).waitFor(); await apply(() => page.getByRole('button', { name: '交付记录（含历史版本）', exact: true }).click(), { view: 'HISTORY' });
    await page.getByPlaceholder('精确词包名', { exact: true }).fill('精确词包-甲'); let data = await query({ packageName: '精确词包-甲' }); assert.equal(data.total, 63); assert.ok(data.items.every(item => item.packageName === '精确词包-甲'));
    await page.getByPlaceholder('精确词包名', { exact: true }).fill('精确词包'); data = await query({ packageName: '精确词包' }); assert.equal(data.total, 0);
    await page.getByPlaceholder('精确词包名', { exact: true }).fill(''); await page.getByPlaceholder('甲方批次编号', { exact: true }).fill('b'.repeat(32)); data = await query({ clientBatchCode: 'b'.repeat(32) }); assert.equal(data.total, 62); assert.ok(data.items.every(item => item.clientBatchCode === 'b'.repeat(32))); await page.getByPlaceholder('甲方批次编号', { exact: true }).fill('');
    for (const [label, token] of [['未汇总保存', 'NO'], ['已汇总保存', 'YES'], ['全部', 'ALL']]) { await select('汇总保存', label); data = await query({ archiveState: token }); assert.equal(data.total, rows.filter(row => token === 'ALL' || Boolean(row.archivedAt) === (token === 'YES')).length); }
    for (const [label, token] of [['历史版本', 'HISTORICAL'], ['版本更新待重交', 'UPDATED'], ['全部版本情况', 'ALL']]) { await select('版本情况', label); data = await query({ versionState: token }); assert.equal(data.total, rows.filter(row => token === 'ALL' || token === 'HISTORICAL' && !row.isCurrent || token === 'UPDATED' && row.versionUpdated).length); }
    for (const [token, total] of [['17', 2], ['合成精确交付 17', 1], ['JF-beta', 62]]) { await page.getByRole('textbox', { name: '搜索交付内容', exact: true }).fill(token); data = await query({ search: token }); assert.equal(data.total, total); }
    await page.getByRole('textbox', { name: '搜索交付内容', exact: true }).fill(''); await query({ search: '' }); const nav = page.getByRole('navigation', { name: '任务列表分页', exact: true });
    data = await apply(() => nav.getByRole('button', { name: '下一页', exact: true }).click(), { offset: '20' }); assert.deepEqual(data.items.map(item => item.taskId), Array.from({ length: 20 }, (_, i) => i + 21)); data = await apply(() => nav.getByRole('button', { name: '尾页', exact: true }).click(), { offset: '120' }); assert.deepEqual(data.items.map(item => item.taskId), [121, 122, 123, 124, 125]); assert.ok(await nav.getByRole('button', { name: '下一页', exact: true }).isDisabled()); await apply(() => nav.getByRole('button', { name: '上一页', exact: true }).click(), { offset: '100' }); await apply(() => nav.getByRole('button', { name: '首页', exact: true }).click(), { offset: '0' });
    for (const size of [50, 100, 20]) { data = await apply(() => select('每页条数', `${size} 条 / 页`), { limit: size, offset: '0' }); assert.equal(data.items.length, size); }
    await page.goto(`${origin}/user`); await page.getByRole('checkbox', { name: '选择交付任务 2', exact: true }).waitFor(); assert.equal(await page.getByRole('combobox', { name: '汇总保存', exact: true }).count(), 0); assert.equal(await page.getByPlaceholder('精确词包名', { exact: true }).count(), 0); assert.equal(await page.getByPlaceholder('甲方批次编号', { exact: true }).count(), 0);
    assert.deepEqual(errors, []); assert.deepEqual(unexpected, []); await page.screenshot({ path: join(out, 'delivery-filter-positive-pass.png'), fullPage: true }); await writeFile(join(out, 'shared-delivery-filter-browser-evidence.json'), JSON.stringify({ evidenceType: 'UI_HTTP_FIXTURE', modelCalls: 0, featureIds: ['F-DELIVERY-006', 'F-DELIVERY-007', 'F-DELIVERY-009', 'F-DELIVERY-017'], scope: 'positive exactpackage/clientbatch/query/task/batch filters; all archive/version branches independent125rowmembership;20/50/100 and first/prev/next/last;USERhiddenAdmincontrols', requests, evidence }, null, 2));
  } finally { await browser.close(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); await rm(root, { recursive: true, force: true }); }
});
